config/routes.rb
Rails.application.routes.draw do
  # get 'teachers/index'
  # get 'teachers/show'
  # get 'students/index'
  # get 'students/show'
resources "houses" , only: %i[index show]
  root to: "houses#index"
  # get "houses", to: "houses#index"
  # get "houses/:id", to: "houses#show", id: /\d+/, as: "house"
  # Defines the root path route ("/")
  # root "posts#index"

  resources "students", only: %i[index show]
  resources "teachers", only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
    has_many :students
    has_many :teachers
    validates :name, :points , presence:true
    validates :points, numericality: {only_integer: true}
end

app/models/school_class.rb
class SchoolClass < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :house
  has_many :school_class
  has_many :teachers , through: :school_class
  validates:name, presence:true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :house
  has_many :school_class
  has_many :students ,through: :school_class
  validates:name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.includes(:house).order(:name)
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.includes(:house).order(:name)
  end

  def show
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/houses/index.html.erb
<% if @houses.empty? %>
   <p> all houses are empty !</p>
<% else %>
    <% @houses.each do |house| %>
    <h2><%= house.name %></h2> 
    <p>
    There are <%= house.students.count %> students and <%= house.teachers.count %> teachers in this house.
    </p>

    <p>
    The Students here have acculumated <% house.points %> points.
    </p>
    <p>
    Learn More about this  <%= link_to "house #{house.name}" , house %>
    <p>

    <% end %>
<% end %>

app/views/houses/show.html.erb
<h2><%= @house.name %></h2>
<p>
There are <%= @house.students.count %> students and <%=@house.teachers.count%> teachers in <%= @house.name %> house
</p>

<p>
The students and teachers of <%= @house.name %> have collected <%= @house.points %> points
</p>

<h3>
<% if @house.students.empty? %>
  <p>
  There is no one in the house
  </p>
<% else %>
  <h3> List of Students: </h3>
   <ul>
    <% @house.students.each do |student|%>
    <li> <%= link_to student.name , student_path(student) %></li>
    <% end %>
   </ul>
<% end %>
 
<h3>List of Teachers</h3>
   <% if @house.teachers.empty? %>
     
    <p> There are no teachers in this house</p>
  
   <% else %>
   
  <% @house.teachers.each do |teacher|%>
    <li>
      <%= link_to teacher.name, teacher_path(teacher) %>
      
    </li>
    <%end%>
</ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hogwarts School WebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <div class = "container">
      <header>
        <h1>Hogwarts School of Witches and Wizards</h1>
      </header>
      <h3>
      <%= link_to 'Home', root_path %> | 
      <%= link_to 'Students' , students_path %> | 
      <%= link_to 'Teachers', teachers_path %>
      </h3>
      <%= yield %>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h1>List of Students </h1>
<% if @students.empty? %>
    <p> There are no Students in the house </p>
<% else %>
  <ul>
     <% @students.each do |student|%>
        <li><%= link_to student.name, student_path(student) %> of House 
        <%= link_to student.house.name , student.house %>
        </li> 

    <%end%>
  </ul>

<% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<p>
This Student belongs to <%= link_to @student.house.name, house_path(@student.house)%> House 
</p>
<h2> Teachers of <%=@student.name %></h2>
<% if @student.house.teachers.empty?%>
  <p> There are no teachers for <%= @student.name %></p>
<%else %>
 <% @student.house.teachers.each do |teacher|%>
    <li>
     <%= link_to teacher.name, teacher_path(teacher) %>
    </li>
  <% end %>
<%end%>

<h2>Class scheduled for : <%= @student.name%></h2>
<%if @student.school_class.empty?%>
  <p>No class scheduled :)
  </br>
  Enjoy!!
  </p>
<%else%>
  <% @student.school_class.each do |school|%>
    <li>
    <%= link_to school.teacher.name, school.teacher %> at 
    <%= school.class_time%>
    </li>
  <%end%>
<%end%>

app/views/teachers/index.html.erb
<h1>List of Teachers</h1>
<% if @teachers.empty? %>
  <p> There are no Teachers </p>
<% else %>
 <ul>
  <% @teachers.each do |teacher| %>
    <li><%= link_to teacher.name, teacher_path(teacher) %> is in the house
    <%= link_to teacher.house.name , teacher.house %>
    </li>
    <% end %>

 </ul>
<% end %>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>
<p>
This Teacher belongs to <%= link_to @teacher.house.name, house_path(@teacher.house) %>
</p>
<h2>Students of <%= @teacher.name %> : </h2>
<% if @teacher.house.students.empty?%>
  <p>There are no Student assigned to <%= @teacher.name%></p>
<%else%>
  <% @teacher.house.students.each do |student|%>
    <li>
    <%= link_to student.name, student_path(student)%>
    </li>
  <%end%>
<%end%>

<h2>Students who have a Class scheduled with : <%= @teacher.name%></h2>
<% if @teacher.school_class.empty?%>
   <p>There no class scheduled currently :)</p>
<%else%>
  <% @teacher.school_class.each do |school|%>
    <li>
    <%= link_to school.student.name, school.student %> at 
    <%= school.class_time %>
    </li>
    <%end%> 
<%end%>